stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"

build_job:
  stage: build
  image: node:18-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main

deploy_pages:
  stage: deploy
  script:
    - echo "Deploying to Gitee Pages"
  artifacts:
    paths:
      - dist/
  only:
    - main 